### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by kendellfab** [diamondburned/gotk4-sourceview#1]
First, thanks for the work you've done on these libraries.

I'm getting a large amount of errors when compiling.  Any help would be appreciated, thanks.

# github.com/diamondburned/gotk4-sourceview/pkg/gtksource/v5
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletion.go:80:66: provider.Native undefined (type CompletionProviderer has no field or method Native)
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletion.go:182:66: provider.Native undefined (type CompletionProviderer has no field or method Native)
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:67:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:89:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:122:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:123:41: gicon.Native undefined (type gio.Iconner has no field or method Native)
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:136:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:151:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:166:53: cannot convert self.Widget.Native() (type gtk.NativeSurfacer) to type unsafe.Pointer
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:167:52: paintable.Native undefined (type gdk.Paintabler has no field or method Native)
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220123000334-af2cc9f33426/gtksource/v5/gtksourcecompletioncell.go:167:52: too many errors

**Comment by diamondburned** [comment]
Seems like this was generated with an old version of `gotk4`. I'll regenerate it in a bit.

**Comment by diamondburned** [comment]
Latest is now regenerated to use latest `gotk4`. Everything is confirmed to build aagin.

**Comment by kendellfab** [comment]
That is great. Thank you!
